# Generated by Django 3.1.7 on 2021-03-25 11:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(max_length=50)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('content', models.TextField(max_length=100000)),
                ('img', models.ImageField(upload_to='images')),
                ('write_date', models.DateTimeField(auto_now_add=True)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('publish_stat', models.CharField(choices=[('p', 'published'), ('d', 'drafted')], max_length=1)),
            ],
        ),
    ]
