# Generated by Django 3.1.7 on 2021-03-25 12:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210325_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='publish_stat',
        ),
        migrations.AddField(
            model_name='post',
            name='publish_status',
            field=models.CharField(choices=[('p', 'published'), ('d', 'drafted')], default='p', max_length=1, verbose_name='وضعیت'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=100000, verbose_name='مطالب'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(upload_to='images', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subject',
            field=models.CharField(max_length=50, verbose_name='تیتر'),
        ),
    ]
