# Generated by Django 3.1.7 on 2021-03-25 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210325_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publish_date',
            new_name='published',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='publish_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='update_date',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='write_date',
            new_name='wrote',
        ),
    ]
