# Generated by Django 3.1.7 on 2021-04-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_category_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('pub', 'Public'), ('hid', 'Hidden'), ('drf', 'Drafted')], default='pub', max_length=3),
        ),
    ]
