# Generated by Django 3.1.7 on 2021-04-09 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210409_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sub_cat',
        ),
        migrations.AddField(
            model_name='category',
            name='parent_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='blog.category', verbose_name='سردسته'),
        ),
    ]
